#!/usr/bin/env bash
# Storage capacity by volume.
# Sample output:
# Name     Used% Used Total
# /volume1 66% 104T 158T
# /volume2 67% 94T 140T
# /volume3 1% 77M 123T

disk_storage() {

  # df human-readable, all |
  # awk to skip first line, then print header, fields of interest

  storage=$(df -ha /volume* |awk '(NR>1) {print $6, $5, $3, $2}')

    printf "%s\n" "Name     Used% Used Total"
    printf "%s\n" "$storage"
}

disk_storage
