#!/usr/bin/env bash
# Extract ethernet device assignment, MAC address, and IP address.
# Print in ascending order.
# Sample output:
# eth0: 00:11:32:79:95:1b 169.254.21.82/16
# eth1: 00:11:32:79:95:1c 169.254.105.132/16
# Device "eth2" does not exist.
# Device "eth3" does not exist.
# Device "eth4" does not exist.
# Device "eth5" does not exist.

ethernet_devices() {
  # Iterate through ethernet devices (0-5) via 'ip' command
  # awk to match eth and extract column contents.

  for i in $(seq -w 0 5 $END);
    do ip addr show eth$i |awk '/eth/ {print $2}';
  printf "\n"
  done
  
}

ethernet_devices

# Iterate through ethernet devices (0-5) via 'ip' command
# awk to match eth and extract column contents.

ethernet_devices() {

  for i in $(seq -w 0 5); do

  # Assign iterative num to ip addr show
  # send standard output to /dev/null

    if ip addr show eth"$i" > /dev/null 2>&1; then

      # awk to extract 'ether' and print second column
      ether=$(ip link show eth$i | awk '/ether/ {print $2}')

      # awk to extract 'inet' and print second column
      inet=$(ip addr show eth$i | awk '/inet / {print $2}')

  # print
    printf "%s\n" "eth$i: $ether $inet"
  else
    printf "%s\n" "Device \"eth$i\" does not exist."
  fi
done

}
