#!/usr/bin/env bash

# List connected (172,168) subnet IP(s).
# Sample output:
# eth0 172.22.114.159/23
# eth1 169.254.84.242/16

IP_address() {

  # IP addr show|
  # awk match eth 0-5 AND 172
  # print field 2

  IP=$(ip addr show |awk '/eth[0-5]/ && /172/ || /169/ {print $1,$2}')
    printf "%s\n" "$IP"
}

IP_address
