#!/usr/bin/env bash
# List all IP addressed for eth devices.
# Sample output:
# eth0 169.254.21.82/16
# eth1 169.254.105.132/16
# eth2 169.254.69.117/16
# eth3 169.254.206.44/16
# eth4 172.22.115.242/23
# eth5 169.254.4.191/16

IP_address() {

  # IP addr show|
  # awk match eth[0-5] AND inet
  # print fields 7,2
  # sort

  IP=$(ip addr show |awk '/eth[0-5]/ && /inet/ {print $7, $2 |"sort"}' )
    printf "%s\n" "$IP"
}

IP_address
