#!/usr/bin/env bash

# List connected (172,168) subnet IP(s).
# Sample output:
#eth3 169.254.206.44/16
#eth2 169.254.69.117/16
#eth1 169.254.105.132/16
#eth0 169.254.21.82/16
#eth5 169.254.4.191/16
#eth4 172.22.115.242/23

IP_address() {

  # IP addr show|
  # awk match eth[0-5] AND inet
  # print fields 7,2

  IP=$(ip addr show |awk '/eth[0-5]/ && /inet/ {print $7, $2}' |sort)
    printf "%s\n" "$IP"
}

IP_address

# TODO: sort out why eth* devices aren't ordered.
# As an alternative approach: 
# ifconfig -a |awk '/eth[0-5]/ || /inet addr/ {print $1, $2}'
# but needs a trim

#ip --brief address show |awk '/eth[0-5]/ {print $1, $3}'|sort
#Sample output:
#eth0 DOWN 169.254.21.82/16
#eth1 DOWN 169.254.105.132/16
#eth2 DOWN 169.254.69.117/16
#eth3 DOWN 169.254.206.44/16
#eth4 UP 172.22.115.242/23
#eth5 UP 169.254.4.191/16
# --> DSM 6 NO --brief option
