#!/usr/bin/env bash
# Get IP address AND MAC address of active Ethernet devices.
# Sample output: 
# eth5: 00:11:32:79:95:20 169.254.4.191/16
# eth4: 00:11:32:79:95:1f 172.22.115.242/23



# Get 'eth' devices that have a status of 'UP'

interfaces=$(ip addr show | awk '/eth/ && /state UP/ {print $2}')

# Iterate through the interfaces
for interface in $interfaces; do

# Get MAC address AND IP address (not IPv6)

  mac=$(ip addr show $interface | awk '/link\/ether/ {print $2}')
  ip=$(ip addr show $interface | awk '/inet/ {print $2;exit;}')

  printf "%s\n" "$interface $mac $ip"

done
