#!/usr/bin/env bash
# Get MAC address and IP address of active Ethernet devices.
# Sample output: 
# eth5: 00:11:32:79:95:20 169.254.4.191/16
# eth4: 00:11:32:79:95:1f 172.22.115.242/23

network_stats() {
  # Parse output of ip addr using awk to extract:
  # 'eth' with status of 'UP'

  interfaces=$(ip addr show | awk '/eth/ && /state UP/ {print $2}')

  # Iterate through interfaces

  for interface in $interfaces; do

  # use awk to parse MAC address ('link ether') 
  # use awk to parse IP address ('inet' NOT 'inet IPv6', so exit after first match)

    mac=$(ip addr show $interface | awk '/link\/ether/ {print $2}')
    ip=$(ip addr show $interface | awk '/inet/ {print $2;exit;}')

  printf "%s\n" "$interface $mac $ip"

done
}

network_stats

# TODO: sort output be numerical eth order.
