#!/usr/bin/env bash
# Get IP address AND MAC address of active Ethernet devices.
# TODO: Trim inactive from standard output.

# Get 'eth' devices with state 'UP' 

interfaces=$(ip addr show | awk '/eth/ && /state UP/ {print $2}')
printf "%s\n" "$interfaces"

# Iterate through the interfaces

for interface in $interfaces; do
  
  # Get the IP address, MAC address and Ethernet number

   ip=$(ip addr show $interface | awk '/inet/ {print $2}')
   mac=$(ip addr show $interface | awk '/link\/ether/ {print $2}')

   printf "%s\n" "$interface $mac $ip"

done


# Get 'eth' devices that have a status of 'UP'

interfaces=$(ip addr show | awk '/eth/ && /state UP/ {print $2}')

# Iterate through the interfaces
for interface in $interfaces; do

# Get MAC address AND IP address (not IPv6)

  mac=$(ip addr show $interface | awk '/link\/ether/ {print $2}')
  ip=$(ip addr show $interface | awk '/inet/ {print $2;exit;}')

  printf "%s\n" "$interface $mac $ip"

done
