#!/usr/bin/env bash
# Display header message.

write_header() {

  name=$1; shift;

  printf "%s\\n""--------------------\\n$name%s\\n--------------------\\n"
  printf "%s\\n" "$@"
}

write_header "Sample Header" "Sample Output"
