#!/usr/bin/env bash
# Synology system information.

# Field array.

FIELD=(
'Basic Information'
'Server name:'
'DSM version:'
'Hardware'
'Serial number:'
'Model name:'
'CPU:'
'Total physical memory:'
'Network'
'MAC address:'
'IP address:'
'Time'
'System time:'
'Uptime:'
)

# Display header message.

write_header() {

  name=$1; shift;

  printf "%s\\n""--------------------\\n$name%s\\n--------------------\\n"
  printf "%s\\n" "$@"
}

# Fully-qualified domain name.

host() {

  host=$(hostname -f)
    printf "%s\n" "${FIELD[1]} $host"
}

# Extract DSM product version.

dsm_version() {

  dsm=$(awk -F '"' 'NR==6 {print $2}' /etc.defaults/VERSION)
    printf "%s\n" "${FIELD[2]} $dsm"
}

# Synology serial no.

serial_number() {

  serial=$(cat /proc/sys/kernel/syno_serial)
    printf "%s\n" "${FIELD[4]} $serial"
}

# Synology model name.

model_name() {
  
  model=$(cat /proc/sys/kernel/syno_hw_version)
    printf "%s\n" "${FIELD[5]} $model"
}

# Extract CPU model name.

cpu_info() {

  cpu=$(awk '/model name/ || /Processor/ { sub(/^.*: /, ""); print; exit}' /proc/cpuinfo)
    printf "%s\n" "${FIELD[6]} $cpu"
}

# Total memory (gB) using kB to gB conversion.

memory() {

  gB=$(awk '/MemTotal/ {print $2/1024/1024}' /proc/meminfo)
    printf "%s\n" "${FIELD[7]} $gB gB"
}

# Get MAC address for onboard NIC(s).

mac_address() {

  mac=$(ifconfig -a |awk '/eth[0-5]/ && /HWaddr/ {print $1, $5}')
    printf "%s\n" "${FIELD[9]} $mac"
}

# Main.

main() {

  write_header "${FIELD[0]}"
  host
  dsm_version
  write_header "${FIELD[3]}"
  serial_number
  model_name
  cpu_info
  memory
  write_header "${FIELD[8]}"
  mac_address
}

main "$@"
